-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/stable_points.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/stable_points (
  sp_revision INTEGER NOT NULL,
  sp_page INTEGER NOT NULL,
  sp_time BLOB NOT NULL,
  sp_user INTEGER NOT NULL,
  sp_comment CLOB DEFAULT NULL,
  PRIMARY KEY(sp_revision)
);
