-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ContentStabilization/db/stable_file_transclusions_source_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__stable_file_transclusions AS
SELECT
  sft_revision,
  sft_page,
  sft_file_revision,
  sft_file_name,
  sft_file_timestamp,
  sft_file_sha1
FROM /*_*/stable_file_transclusions;
DROP TABLE /*_*/stable_file_transclusions;


CREATE TABLE /*_*/stable_file_transclusions (
    sft_revision INTEGER NOT NULL, sft_page INTEGER NOT NULL,
    sft_file_revision INTEGER NOT NULL,
    sft_file_name BLOB NOT NULL, sft_file_timestamp BLOB NOT NULL,
    sft_file_sha1 BLOB NOT NULL, sft_file_source BLOB DEFAULT '' NOT NULL
  );
INSERT INTO /*_*/stable_file_transclusions (
    sft_revision, sft_page, sft_file_revision,
    sft_file_name, sft_file_timestamp,
    sft_file_sha1
  )
SELECT
  sft_revision,
  sft_page,
  sft_file_revision,
  sft_file_name,
  sft_file_timestamp,
  sft_file_sha1
FROM
  /*_*/__temp__stable_file_transclusions;
DROP TABLE /*_*/__temp__stable_file_transclusions;

CREATE UNIQUE INDEX sft_revision_file_name_timestamp_source ON /*_*/stable_file_transclusions (
    sft_revision, sft_file_name, sft_file_timestamp,
    sft_file_source
  );
