-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/ContentStabilization/db/stable_file_transclusions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/stable_file_transclusions (
  sft_revision INTEGER NOT NULL, sft_page INTEGER NOT NULL,
  sft_file_revision INTEGER NOT NULL,
  sft_file_name BLOB NOT NULL, sft_file_timestamp BLOB NOT NULL,
  sft_file_sha1 BLOB NOT NULL, sft_file_source BLOB DEFAULT '' NOT NULL
);

CREATE UNIQUE INDEX sft_revision_file_name_timestamp_source ON /*_*/stable_file_transclusions (
  sft_revision, sft_file_name, sft_file_timestamp,
  sft_file_source
);
