-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/stable_transclusions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/stable_transclusions (
  st_revision INTEGER NOT NULL, st_page INTEGER NOT NULL,
  st_transclusion_revision INTEGER NOT NULL,
  st_transclusion_namespace INTEGER NOT NULL,
  st_transclusion_title BLOB NOT NULL
);

CREATE UNIQUE INDEX st_revision_transclusion_revision ON /*_*/stable_transclusions (
  st_revision, st_transclusion_revision
);
