-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ContentStabilization/db/stable_transclusions_remove_unique_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__stable_transclusions AS
SELECT
  st_revision,
  st_page,
  st_transclusion_revision,
  st_transclusion_namespace,
  st_transclusion_title,
  st_transclusion_source
FROM /*_*/stable_transclusions;
DROP TABLE /*_*/stable_transclusions;


CREATE TABLE /*_*/stable_transclusions (
    st_revision INTEGER NOT NULL, st_page INTEGER NOT NULL,
    st_transclusion_revision INTEGER NOT NULL,
    st_transclusion_namespace INTEGER NOT NULL,
    st_transclusion_title BLOB NOT NULL,
    st_transclusion_source BLOB NOT NULL
  );
INSERT INTO /*_*/stable_transclusions (
    st_revision, st_page, st_transclusion_revision,
    st_transclusion_namespace, st_transclusion_title,
    st_transclusion_source
  )
SELECT
  st_revision,
  st_page,
  st_transclusion_revision,
  st_transclusion_namespace,
  st_transclusion_title,
  st_transclusion_source
FROM
  /*_*/__temp__stable_transclusions;
DROP TABLE /*_*/__temp__stable_transclusions;
