-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ContentStabilization/db/stable_points_indices_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__stable_points AS
SELECT  sp_revision,  sp_page,  sp_time,  sp_user,  sp_comment
FROM  /*_*/stable_points;
DROP  TABLE  /*_*/stable_points;
CREATE TABLE  /*_*/stable_points (    sp_revision INTEGER NOT NULL,    sp_page INTEGER NOT NULL,    sp_time BLOB NOT NULL,    sp_user INTEGER NOT NULL,    sp_comment CLOB DEFAULT NULL,    PRIMARY KEY(sp_revision)  );
INSERT INTO  /*_*/stable_points (    sp_revision, sp_page, sp_time, sp_user,    sp_comment  )
SELECT  sp_revision,  sp_page,  sp_time,  sp_user,  sp_comment
FROM  /*_*/__temp__stable_points;
DROP  TABLE /*_*/__temp__stable_points;
CREATE UNIQUE INDEX sp_revision_index ON  /*_*/stable_points (sp_revision);
CREATE INDEX sp_page ON  /*_*/stable_points (sp_page);
CREATE INDEX sp_time ON  /*_*/stable_points (sp_time);
CREATE INDEX sp_user ON  /*_*/stable_points (sp_user);