-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/stable_file_transclusions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/stable_file_transclusions (
  sft_revision INT NOT NULL,
  sft_page INT NOT NULL,
  sft_file_revision INT NOT NULL,
  sft_file_name VARBINARY(255) NOT NULL,
  sft_file_timestamp BINARY(14) NOT NULL,
  sft_file_sha1 VARBINARY(32) NOT NULL,
  UNIQUE INDEX sft_revision_file_name_timestamp (
    sft_revision, sft_file_name, sft_file_timestamp
  )
) /*$wgDBTableOptions*/;
