-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ContentStabilization/db/stable_transclusions_remove_unique_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX st_revision_transclusion_revision ON /*_*/stable_transclusions;
