-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/stable_points.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/stable_points (
  sp_revision INT NOT NULL,
  sp_page INT NOT NULL,
  sp_time BINARY(14) NOT NULL,
  sp_user INT NOT NULL,
  sp_comment LONGTEXT DEFAULT NULL,
  PRIMARY KEY(sp_revision)
) /*$wgDBTableOptions*/;
