-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/stable_file_points.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/stable_file_points (
  sfp_revision INT NOT NULL,
  sfp_page INT NOT NULL,
  sfp_file_timestamp BINARY(14) NOT NULL,
  sfp_file_sha1 VARBINARY(32) NOT NULL,
  PRIMARY KEY(sfp_revision)
) /*$wgDBTableOptions*/;
