-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ContentStabilization/db/stable_points_page_revision_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE INDEX sp_page_revision_index ON /*_*/stable_points (sp_page, sp_revision);
