-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ContentStabilization/db/stable_transclusions_source_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX st_revision_transclusion_revision ON /*_*/stable_transclusions;
ALTER TABLE /*_*/stable_transclusions
  ADD st_transclusion_source VARBINARY(255) DEFAULT '' NOT NULL;

CREATE UNIQUE INDEX st_revision_transclusion_revision ON /*_*/stable_transclusions (
    st_revision, st_transclusion_revision,
    st_transclusion_source
  );
