-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ContentStabilization/db/stable_file_transclusions_source_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX sft_revision_file_name_timestamp ON /*_*/stable_file_transclusions;
ALTER TABLE /*_*/stable_file_transclusions
  ADD sft_file_source VARBINARY(255) DEFAULT '' NOT NULL;

CREATE UNIQUE INDEX sft_revision_file_name_timestamp_source ON /*_*/stable_file_transclusions (
    sft_revision, sft_file_name, sft_file_timestamp,
    sft_file_source
  );
