-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/stable_file_points.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE stable_file_points (
  sfp_revision INT NOT NULL,
  sfp_page INT NOT NULL,
  sfp_file_timestamp TIMESTAMPTZ NOT NULL,
  sfp_file_sha1 TEXT NOT NULL,
  PRIMARY KEY(sfp_revision)
);
