-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ContentStabilization/db/stable_transclusions_source_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX st_revision_transclusion_revision;
ALTER TABLE stable_transclusions
  ADD st_transclusion_source TEXT DEFAULT '' NOT NULL;

CREATE UNIQUE INDEX st_revision_transclusion_revision ON stable_transclusions (
  st_revision, st_transclusion_revision,
  st_transclusion_source
);
