-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/ContentStabilization/db/stable_points.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE stable_points (
  sp_revision INT NOT NULL,
  sp_page INT NOT NULL,
  sp_time TIMESTAMPTZ NOT NULL,
  sp_user INT NOT NULL,
  sp_comment TEXT DEFAULT NULL,
  PRIMARY KEY(sp_revision)
);

CREATE INDEX sp_page_revision_index ON stable_points (sp_page, sp_revision);
