-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ContentStabilization/db/stable_points_indices_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE UNIQUE INDEX sp_revision_index ON stable_points (sp_revision);
CREATE INDEX sp_page ON stable_points (sp_page);
CREATE INDEX sp_time ON stable_points (sp_time);
CREATE INDEX sp_user ON stable_points (sp_user);