-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/stable_file_transclusions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE stable_file_transclusions (
  sft_revision INT NOT NULL, sft_page INT NOT NULL,
  sft_file_revision INT NOT NULL, sft_file_name TEXT NOT NULL,
  sft_file_timestamp TIMESTAMPTZ NOT NULL,
  sft_file_sha1 TEXT NOT NULL
);

CREATE UNIQUE INDEX sft_revision_file_name_timestamp ON stable_file_transclusions (
  sft_revision, sft_file_name, sft_file_timestamp
);
