-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/stable_transclusions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE stable_transclusions (
  st_revision INT NOT NULL, st_page INT NOT NULL,
  st_transclusion_revision INT NOT NULL,
  st_transclusion_namespace INT NOT NULL,
  st_transclusion_title TEXT NOT NULL
);

CREATE UNIQUE INDEX st_revision_transclusion_revision ON stable_transclusions (
  st_revision, st_transclusion_revision
);
